### ISSUE TITLE
Issue with streamlit.cli from conda installation

### ISSUE THREAD

**Issue by eggrandio** [mmcguffi/pLannotate#32]
Hi,

I have installed pLannotate from conda and I am getting the following error message:

File "(...)/miniconda3/envs/plann/lib/python3.11/site-packages/plannotate/pLannotate.py", line 5, in <module>
    import streamlit.cli
ModuleNotFoundError: No module named 'streamlit.cli'

According to this [issue ](https://github.com/streamlit/streamlit/issues/5146#issuecomment-1223306586)in github, it seems that:
"If anyone stumbles across this, the streamlit.cli module was moved to streamlit.web.cli."

Best,

Edit: if I install it with mamba, it gets a different version of streamlit that works. But sometimes I get an error with altair version 5 (if it gets version 4, it works). Maybe "fixing" the versions of streamlit and altair in the recipe should fix the problem?

**Comment by jeffreybarrick** [comment]
I think @mmcguffi is working to update the conda install and the other internal links to reflect the repository change.

**Comment by mmcguffi** [comment]
Very sorry about the trouble @madeleinevlt! I'll push some fixes soon -- you're correct that the git repository changed, which leads to some issues, but it appears other deps are causing problems too, at least via conda installation

One other solution in the meantime (which will also ensure that previous conda installs work) is for @jeffreybarrick to slightly change the url of the barricklab fork so that url will always direct to the new location

**Comment by mmcguffi** [comment]
Thank you for the investigation and help @eggrandio and @madeleinevlt -- sorry for the headaches this caused. There is a new version of plannotate on conda that works (v1.2.1). I also included automated tests that will run once a month, so if something in the dependencies (or anything else) breaks, at least I'll be warned
