### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by NathanNgu** [mmcguffi/pLannotate#41]
Hello,
I have been having issues with pLannotate installation.

When I attempt the conda version I get an issue with blast
![image](https://github.com/mmcguffi/pLannotate/assets/34899593/b7748d0e-fcab-4779-88b1-818970667ab6)

When I attempt the other file version, I get a similar issue.
![image](https://github.com/mmcguffi/pLannotate/assets/34899593/0fb33071-23a9-433d-a1b6-c97ae2723aa6)

I have the most recent version of conda 24.1.2 but it still seems like the correct versions of multiple dependencies don't exist on the proper channels

If anyone knows why this issue persists, please let me know. Thanks!

**Comment by mmcguffi** [comment]
Hi @NathanNgu unfortunately pLannotate is not supported on Windows -- at the very least there are some paths that use linux/unix notation instead of windows notation. There are very likely other breaking problems with windows as well

That said, I highly recommend installing and using [Windows Subsystem for Linux (WSL) ](https://learn.microsoft.com/en-us/windows/wsl/install), which essentially gives you linux on your windows machine. While I rarely use Windows, this is how I have always done any kind of bioinformatics on that platform
